### PR TITLE
[TEST] Fixes /connections/org.pentaho.commons.connection.DataUtilitie…

### PR DESCRIPTION
**Pull request by LeonardoCoelho71950**
…sNumberTest.toNumbersDouble[0]

@pentaho/tatooine @pentaho-lmartins 
When we are testing DataUtilities.toNumbers(), we need to make sure that the NumberFormat is consistent.

### CODE REVIEW

**Comment by pentaho-lmartins** [comment]
Can you write another test with PT and a number format like 1.232,48?

**Comment by LeonardoCoelho71950** [comment]
@pentaho-lmartins On my way

**Comment by pentaho-lmartins** [comment]
Can you remove all the `$NON-NLS` stuff?

**Comment by LeonardoCoelho71950** [comment]
Done @pentaho-lmartins

**Pull request merged**
