### PR TITLE
Pdb 1427

### PR DESCRIPTION
**Pull request by SergeyTravin**
@bytekast, @kolinus could you please review

### CODE REVIEW

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  src/org/pentaho/commons/connection/marshal/MarshallableColumnNames.java
  src/org/pentaho/commons/connection/memory/MemoryMetaData.java
  src/org/pentaho/commons/connection/memory/MemoryResultSet.java
  test/org/pentaho/commons/connection/DataTest.java
  test/org/pentaho/commons/connection/DataUtilitiesNumberTest.java
  test/org/pentaho/commons/connection/DataUtilitiesTest.java
  test/org/pentaho/commons/connection/MetaDataUtilTest.java
  test/org/pentaho/commons/connection/SimpleStreamSourceTest.java
  test/org/pentaho/commons/connection/marshal/MarshallableResultSetTest.java
  test/org/pentaho/commons/connection/memory/MemoryMetaDataTest.java
  test/org/pentaho/commons/connection/memory/MemoryResultSetTest.java
  test/org/pentaho/commons/connection/test/DataTest.java
  test/org/pentaho/commons/connection/test/DataUtilitiesTest.java
  test/org/pentaho/commons/connection/test/MarshallableResultSetTest.java
  test/org/pentaho/commons/connection/test/MemoryResultSetTest.java
  test/org/pentaho/commons/connection/test/MetaDataUtilTest.java
  test/org/pentaho/commons/connection/test/NumberConverterTest.java
  test/org/pentaho/commons/connection/test/StreamSourceTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File test/org/pentaho/commons/connection/memory/MemoryMetaDataTest.java
1. Message: Using the '.*' form of import should be avoided - org.junit.Assert.*. at Line: 15 Column: None

File test/org/pentaho/commons/connection/memory/MemoryResultSetTest.java
1. Message: Using the '.*' form of import should be avoided - org.junit.Assert.*. at Line: 15 Column: None


License header violations:
==========================

1. src/org/pentaho/commons/connection/marshal/MarshallableColumnNames.java

2. src/org/pentaho/commons/connection/memory/MemoryMetaData.java

3. src/org/pentaho/commons/connection/memory/MemoryResultSet.java

4. test/org/pentaho/commons/connection/DataTest.java

5. test/org/pentaho/commons/connection/DataUtilitiesNumberTest.java

6. test/org/pentaho/commons/connection/DataUtilitiesTest.java

7. test/org/pentaho/commons/connection/MetaDataUtilTest.java

8. test/org/pentaho/commons/connection/SimpleStreamSourceTest.java

9. test/org/pentaho/commons/connection/marshal/MarshallableResultSetTest.java

10. test/org/pentaho/commons/connection/memory/MemoryMetaDataTest.java

11. test/org/pentaho/commons/connection/memory/MemoryResultSetTest.java








Unit test coverage change:
============
org.pentaho.commons.connection.memory.MemoryMetaData:
 * instructionPercentCoverageChange : +3.72%
 * branchPercentCoverageChange : +25.00%
 * linePercentCoverageChange : +5.74%
 * complexityPercentCoverageChange : +7.78%
 * methodPercentCoverageChange : +1.44%
    
org.pentaho.commons.connection.memory.MemoryResultSet:
 * instructionPercentCoverageChange :**-3.46%**
 * branchPercentCoverageChange :**-2.17%**
 * linePercentCoverageChange :**-4.20%**
 * complexityPercentCoverageChange :**-5.88%**
 * methodPercentCoverageChange :**-7.14%**

**Comment by pamval** [comment]
@SergeyTravin review the license headers, please and try to understand why we're losing coverage on MemoryResultSet

**Comment by SergeyTravin** [comment]
@pamval license headers for this project are different from another pentaho project, I just update the year. I add the licence header for new file form nearby file.

Should we change the license header if so which  license header should we use for this project? 

The coverage was increasing.

**Comment by pamval** [comment]
LGPL, check the one in pentaho-platform.

From the wingman report, coverage increased for MemoryMetaData but decreased for MemoryResultSet. Is that expected ?

**Comment by SergeyTravin** [comment]
@pamval The license headers was updated according your notes. 
Coveragewas  increased for MemoryMetaData and for MemoryResultSet. could you look again please?
Thanks!

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  ivy.xml
  src/org/pentaho/commons/connection/AbstractPentahoMetaData.java
  src/org/pentaho/commons/connection/ActivationHelper.java
  src/org/pentaho/commons/connection/DataUtilities.java
  src/org/pentaho/commons/connection/IDisposable.java
  src/org/pentaho/commons/connection/ILimitableConnection.java
  src/org/pentaho/commons/connection/IMultiDimensionalMetaData.java
  src/org/pentaho/commons/connection/IMultiDimensionalResultSet.java
  src/org/pentaho/commons/connection/IPeekable.java
  src/org/pentaho/commons/connection/IPentahoConnection.java
  src/org/pentaho/commons/connection/IPentahoDataTypes.java
  src/org/pentaho/commons/connection/IPentahoMetaData.java
  src/org/pentaho/commons/connection/IPentahoResultSet.java
  src/org/pentaho/commons/connection/IPentahoStreamSource.java
  src/org/pentaho/commons/connection/InputStreamDataSource.java
  src/org/pentaho/commons/connection/Messages.java
  src/org/pentaho/commons/connection/MetaDataUtil.java
  src/org/pentaho/commons/connection/PentahoDataTransmuter.java
  src/org/pentaho/commons/connection/SimpleStreamSource.java
  src/org/pentaho/commons/connection/marshal/MarshallableColumnNames.java
  src/org/pentaho/commons/connection/marshal/MarshallableColumnTypes.java
  src/org/pentaho/commons/connection/marshal/MarshallableResultSet.java
  src/org/pentaho/commons/connection/marshal/MarshallableRow.java
  src/org/pentaho/commons/connection/marshal/ResultSetMarshaller.java
  src/org/pentaho/commons/connection/memory/MemoryMetaData.java
  src/org/pentaho/commons/connection/memory/MemoryResultSet.java
  test/org/pentaho/commons/connection/DataTest.java
  test/org/pentaho/commons/connection/DataUtilitiesNumberTest.java
  test/org/pentaho/commons/connection/DataUtilitiesTest.java
  test/org/pentaho/commons/connection/MetaDataUtilTest.java
  test/org/pentaho/commons/connection/SimpleStreamSourceTest.java
  test/org/pentaho/commons/connection/marshal/MarshallableResultSetTest.java
  test/org/pentaho/commons/connection/memory/MemoryMetaDataTest.java
  test/org/pentaho/commons/connection/memory/MemoryResultSetTest.java
  test/org/pentaho/commons/connection/test/DataTest.java
  test/org/pentaho/commons/connection/test/DataUtilitiesTest.java
  test/org/pentaho/commons/connection/test/MarshallableResultSetTest.java
  test/org/pentaho/commons/connection/test/MemoryResultSetTest.java
  test/org/pentaho/commons/connection/test/MetaDataUtilTest.java
  test/org/pentaho/commons/connection/test/NumberConverterTest.java
  test/org/pentaho/commons/connection/test/StreamSourceTest.java



License header violations:
==========================

1. test/org/pentaho/commons/connection/memory/MemoryMetaDataTest.java








Unit test coverage change:
============
org.pentaho.commons.connection.memory.MemoryMetaData:
 * instructionPercentCoverageChange : +3.72%
 * branchPercentCoverageChange : +25.00%
 * linePercentCoverageChange : +5.74%
 * complexityPercentCoverageChange : +7.78%
 * methodPercentCoverageChange : +1.44%
    
org.pentaho.commons.connection.memory.MemoryResultSet:
 * instructionPercentCoverageChange : +0.02%

**Comment by pamval** [comment]
sorry, @SergeyTravin you missed one license header :)

**Comment by SergeyTravin** [comment]
@pamval The header was not missed. It just contains the licence which used in the project before the commit.
The header changed to LGPL.

Couid you review it again, please?

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  ivy.xml
  src/org/pentaho/commons/connection/AbstractPentahoMetaData.java
  src/org/pentaho/commons/connection/ActivationHelper.java
  src/org/pentaho/commons/connection/DataUtilities.java
  src/org/pentaho/commons/connection/IDisposable.java
  src/org/pentaho/commons/connection/ILimitableConnection.java
  src/org/pentaho/commons/connection/IMultiDimensionalMetaData.java
  src/org/pentaho/commons/connection/IMultiDimensionalResultSet.java
  src/org/pentaho/commons/connection/IPeekable.java
  src/org/pentaho/commons/connection/IPentahoConnection.java
  src/org/pentaho/commons/connection/IPentahoDataTypes.java
  src/org/pentaho/commons/connection/IPentahoMetaData.java
  src/org/pentaho/commons/connection/IPentahoResultSet.java
  src/org/pentaho/commons/connection/IPentahoStreamSource.java
  src/org/pentaho/commons/connection/InputStreamDataSource.java
  src/org/pentaho/commons/connection/Messages.java
  src/org/pentaho/commons/connection/MetaDataUtil.java
  src/org/pentaho/commons/connection/PentahoDataTransmuter.java
  src/org/pentaho/commons/connection/SimpleStreamSource.java
  src/org/pentaho/commons/connection/marshal/MarshallableColumnNames.java
  src/org/pentaho/commons/connection/marshal/MarshallableColumnTypes.java
  src/org/pentaho/commons/connection/marshal/MarshallableResultSet.java
  src/org/pentaho/commons/connection/marshal/MarshallableRow.java
  src/org/pentaho/commons/connection/marshal/ResultSetMarshaller.java
  src/org/pentaho/commons/connection/memory/MemoryMetaData.java
  src/org/pentaho/commons/connection/memory/MemoryResultSet.java
  test/org/pentaho/commons/connection/DataTest.java
  test/org/pentaho/commons/connection/DataUtilitiesNumberTest.java
  test/org/pentaho/commons/connection/DataUtilitiesTest.java
  test/org/pentaho/commons/connection/MetaDataUtilTest.java
  test/org/pentaho/commons/connection/SimpleStreamSourceTest.java
  test/org/pentaho/commons/connection/marshal/MarshallableResultSetTest.java
  test/org/pentaho/commons/connection/memory/MemoryMetaDataTest.java
  test/org/pentaho/commons/connection/memory/MemoryResultSetTest.java
  test/org/pentaho/commons/connection/test/DataTest.java
  test/org/pentaho/commons/connection/test/DataUtilitiesTest.java
  test/org/pentaho/commons/connection/test/MarshallableResultSetTest.java
  test/org/pentaho/commons/connection/test/MemoryResultSetTest.java
  test/org/pentaho/commons/connection/test/MetaDataUtilTest.java
  test/org/pentaho/commons/connection/test/NumberConverterTest.java
  test/org/pentaho/commons/connection/test/StreamSourceTest.java










Unit test coverage change:
============
org.pentaho.commons.connection.memory.MemoryMetaData:
 * instructionPercentCoverageChange : +3.72%
 * branchPercentCoverageChange : +25.00%
 * linePercentCoverageChange : +5.74%
 * complexityPercentCoverageChange : +7.78%
 * methodPercentCoverageChange : +1.44%
    
org.pentaho.commons.connection.memory.MemoryResultSet:
 * instructionPercentCoverageChange : +0.02%

**Pull request merged**
